[tool.poetry]
name = "abis-mapping"
version = "0.0.1"
description = "Provides templates and mappings to translate tabular data to ABIS rdf"
authors = ["Gaia Resources <dev@gaiaresources.com.au>"]

[tool.poetry.dependencies]
python = "^3.9"
rdflib = "^6.1.1"
python-slugify = "^6.1.1"
frictionless = {extras = ["excel"], version = "^4.26.1"}

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-bugbear = "^22.3.23"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
